tap "homebrew/bundle"
tap "homebrew/services"

brew "python@3.12"
brew "ansible"
brew "caddy"
brew "dash"
brew "docker", link: false
brew "docker-compose"
brew "fd"
brew "ffmpeg"
brew "gcc"
brew "foreman"
brew "gnu-sed"
brew "git"
brew "git-extras"
brew "go"
brew "shared-mime-info"
brew "imagemagick"
brew "lazygit"
brew "qemu"
brew "lima"
brew "mysql", restart_service: true
brew "neovim"
brew "vim"
brew "node"
brew "node@18"
brew "openjdk"
brew "opensearch"
brew "podman"
brew "podman-compose"
brew "postgresql@15", restart_service: true
brew "rbenv"
brew "rclone"
brew "redis"
brew "ripgrep"
brew "ruby"
brew "tailscale"
brew "tmux"
brew "wget"
brew "youtube-dl"

cask "android-file-transfer"
cask "android-platform-tools"
cask "font-hack-nerd-font"
cask "the-unarchiver"
cask "insomnia"
